BLENDER = $(shell command -v blender-4.2 blender 2>/dev/null | head -n 1)
MAGICK = $(shell command -v magick gm 2>/dev/null | head -n 1)
PYTHON = $(shell command -v python3 python 2>/dev/null | head -n 1)
PCB_LAYERS := GM1 TXT GTO GTS GTL G1 G2 GBL GBS GBO

OUTDIR = output


# Main output: files for both boards
.PHONY: all clean
all: \
	$(OUTDIR)/mainboard.zip \
	$(OUTDIR)/support_board.zip 

clean:
	rm -rf $(OUTDIR)
	$(MAKE) -C primitives clean
	$(MAKE) -C parts clean


# Output parts!
.SECONDARY:

$(OUTDIR)/mainboard.zip: $(OUTDIR)/mainboard.normal.png

# Board output file: part lists, PCB layer files, traces
$(OUTDIR)/%.zip: \
	$(OUTDIR)/%.mouser.txt \
	$(OUTDIR)/%.tinytronics.txt \
	$(OUTDIR)/%.PCB.zip \
	$(OUTDIR)/%.front.traces.png \
	$(OUTDIR)/%.back.traces.png
	rm -f $@
	cd $(OUTDIR) && zip $*.zip $(patsubst $(OUTDIR)/%,%,$^)

# PCB output file: layer files
$(OUTDIR)/%.PCB.zip: \
	$(foreach layer,$(PCB_LAYERS),$(OUTDIR)/%.PCB.$(layer))
	rm -f $@
	cd $(OUTDIR) && zip $*.PCB.zip $(patsubst $(OUTDIR)/%,%,$^)

# PCB layer files and base part overview is generated by generated/compose_<pcb>.py once the parts and primitives are in place
$(OUTDIR)/%.front.svg $(OUTDIR)/%.back.svg $(OUTDIR)/%.PCB.obj $(foreach layer,$(PCB_LAYERS),$(OUTDIR)/%.PCB.$(layer)) $(OUTDIR)/%.parts.txt: generator/compose_%.py $(OUTDIR)/primitives.stamp $(OUTDIR)/parts.stamp
	$(PYTHON) $<

# Trace files are generated by generator/post.py from the board composer output
$(OUTDIR)/%.front.traces.svg $(OUTDIR)/%.back.traces.svg: generator/post.py $(OUTDIR)/%.front.svg $(OUTDIR)/%.back.svg
	$(PYTHON) $< $*

# Part lists are generated by generator/orderlist.py from the board composer output
$(OUTDIR)/%.mouser.txt $(OUTDIR)/%.tinytronics.txt: generator/orderlist.py $(OUTDIR)/%.parts.txt
	$(PYTHON) $< $*


%.png: %.svg
	$(MAGICK) convert $< $@

# Deal with stuff in sub-makes (parts and primitives)
$(OUTDIR)/%.stamp: %/Makefile
	cd $* && $(MAKE) BLENDER=$(BLENDER)
	touch $@

$(OUTDIR)/:
	mkdir -p $@
